### PR TITLE
Make the pip "manager" works on windows.

### PR DESCRIPTION
**Pull request by fstamour**
Tested on Windows 10 under git bash.

### CODE REVIEW

**Comment by kdeldycke** [comment]
Thanks for that PR!

Actually I can't really merge that one as is. The `run()` function needs to be kept within the `meta_package_manager.7h.py` file, as that is a BitBar plugin/script and as such needs to be self-contained.

Also, would you be interested to create a new PR to integrate automated unit tests with AppVeyor?

**Comment by fstamour** [comment]
About AppVeyor, I could try. I'm the inverse of a fan of windows, but I have to use it for work, having something like this project working on Windows would ease my pain 😛 

Could you elaborate on why `run()` needs to stay in the plugin? (Maybe just point to a document if it's already documented somewhere.)

Also, what's the `7h` for in `meta_package_manager.7h.py`?

**Comment by kdeldycke** [comment]
@fstamour The `meta_package_manager.7h.py` script needs to be self-contained. That's a BitBar requirement. I just documented that in a1fca547db18780d1a5a984e7f918a0a2747d2ad.

The `7h` suffix is the way to tell BitBar the refresh cycle of the plugin.

**Comment by kdeldycke** [comment]
Thanks for reintroducing the `run()` method in 84c888210bdd4f6e5230682e917488974e93eeb9, but I'd rather not duplicate that method in both `meta_package_manager.7h.py` and `runner.py` files.

Can you find a way to reuse in `runner.py` the `run()` method from `meta_package_manager.7h.py`?

**Comment by kdeldycke** [comment]
As of v2.9.0 mpm is now supporting pip on windows. See: 6bed381e0ac8c89353b6877d8695f98991bb3218

There's no need for this PR now.

**Pull request closed without merging**
