### PR TITLE
Add snap

### PR DESCRIPTION
**Pull request by autinerd**
[Snap](https://snapcraft.io) is a package manager from Canonical which is for all Linux distributions. The packages contains the necessary dependencies and are stored in an extra directory, so system files are not altered.
Snaps are updated automatically (per default is searches 4 times a day for new updates), so the main purpose is installing, finding und removing snaps. Because installing and removing is not implemented in mpm yet, only searching and listing the installed is there now.

### CODE REVIEW

**Comment by kdeldycke** [comment]
Thanks @autinerd for the contribution!

I'm not familiar with Snap operations. Does it have a way to list all outdated packages? The unittests are currently broken as `mpm` expect the `outdated()` method to be implemented: https://github.com/kdeldycke/meta-package-manager/pull/65/checks?check_run_id=561625154#step:26:593

There's also some other tests broken like the checks around the registered managers: https://github.com/kdeldycke/meta-package-manager/pull/65/checks?check_run_id=561625154#step:26:577

I'll be happy to merge it upstream once unittests pass! :)

**Comment by autinerd** [comment]
Yeah, I've added that, it was not easy to find out the structure of the output.
I will fix all problems with the tests, and then hopefully it all works :)

**Comment by kdeldycke** [comment]
The results are good enough to me. If you do not have anything to add, I'll merge this PR and fix the coding style upstream.

**Comment by kdeldycke** [comment]
OK let's merge this then! :)

**Pull request merged**
