### PR TITLE
Add support for Yarn package manager

### PR DESCRIPTION
**Pull request by Bibernull**

### CODE REVIEW

**Comment by Bibernull** [comment]
@kdeldycke let me know if you want me to rebase.
And welcome back.

**Comment by kdeldycke** [comment]
I like this PR! Can you rebase it, remove commits that were embedded from your previous PR and make a clean commit covering addition of yarn and yarn only? Once this is done I'll merge it right away! :)

**Comment by kdeldycke** [comment]
Thanks @Bibernull for the rebase! We'll wait for the unittests to pass to merge this PR.

In the mean time, can you add steps in the GitHub workflow to install Yarn on each of macOS, Linux and Windows platform. It should be easy:
1. Installation instructions for each platform are detailed at: https://classic.yarnpkg.com/en/docs/install
2. There is plenty of example available. You can use Atom installation steps as a template: https://github.com/kdeldycke/meta-package-manager/blob/develop/.github/workflows/tests.yaml#L52-L64

That way we will have a minimal coverage of your contribution.

**Comment by kdeldycke** [comment]
OK, it's good enough to merge. I'll fix all the remaining issue upstream.

**Pull request merged**
