### PR TITLE
Fix pep257 complaints.

### PR DESCRIPTION
**Pull request by torkelsson**

### CODE REVIEW

**Comment by kdeldycke** [comment]
Thanks for nit-picking my docstrings! You made me realize I'll have to change my habits to stick with PEP257.

**Comment by kdeldycke** [comment]
Just a side note: you should configure your Git client to set your author info (a.k.a. `GIT_{AUTHOR,COMMITTER}_{NAME,EMAIL}` variable). Else you'll never be listed as a contributor there: https://github.com/kdeldycke/meta-package-manager/graphs/contributors

**Comment by torkelsson** [comment]
Yeah I know- The problem of using the same machine for both work and private stuff, with different emails. I  continuously used the wrong one, so I had to set email to "none". Guess I finally should create a pre-commit hook that warns me if it is not set.

**Comment by kdeldycke** [comment]
@torkelsson I consolidated your identity in commit becaa7e8264f5144ee2e5e0c25d30e2c44059e8c.

**Pull request merged**
