### PR TITLE
Optimise cargo search

### PR DESCRIPTION
**Pull request by Hasnep**
Just pulling in some optimisations from my version of the `search` function for cargo. I think this version is about 50% faster from running some simple benchmarks, mostly because of the multiline search which means the regex never tries to search across multiple lines. If this PR is accepted I might look at some other functions to see of they can be sped up as well. :)

### CODE REVIEW

**Comment by kdeldycke** [comment]
Oh. Now that's interesting. There are lot's of instances of that pattern in other places for sure. I did not tried to benchmark your proposal but I believe you! 😁

Let's merge! :)

**Comment by Hasnep** [comment]
Update on this, I've just tried to re-create these improvements with some synthetic benchmarks. I think I was wrong and there is only a small speedup from using `re.MULTILINE`, but the main speed up was actually from changing from `.+` to `\S+`.

Benchmark code:

`benchmark.py`

```python
import re


def create_synthetic_data():
    n = 10000
    package_names = [str((5 + (11 * n) % 6) * chr(97 + (n % 26))) for n in range(n)]
    package_versions = [f"v{n%2}.{n%9}.{n%7}" for n in range(n)]
    return "\n".join(
        [
            f"{name} = {version}"
            for (name, version) in zip(package_names, package_versions)
        ]
    )


def one(data):
    regexp = re.compile(r"(.+) = v(.+)")
    output = regexp.findall(data)
    assert len(output) == 10000
    return output


def two(data):
    regexp = re.compile(r"^(.+) = v(.+)$", re.MULTILINE)
    output = regexp.findall(data)
    assert len(output) == 10000
    return output


def three(data):
    regexp = re.compile(r"(\S+) = v(\S+)")
    output = regexp.findall(data)
    assert len(output) == 10000
    return output
```

```
python3 -mtimeit -n 2000 -s 'import benchmark; data = benchmark.create_synthetic_data()' 'benchmark.one(data)'
2000 loops, best of 5: 4.03 msec per loop
python3 -mtimeit -n 2000 -s 'import benchmark; data = benchmark.create_synthetic_data()' 'benchmark.two(data)'
2000 loops, best of 5: 3.95 msec per loop
python3 -mtimeit -n 2000 -s 'import benchmark; data = benchmark.create_synthetic_data()' 'benchmark.three(data)'
2000 loops, best of 5: 3.61 msec per loop
```

**Comment by kdeldycke** [comment]
Oh wow. Thanks @Hasnep for taking the time to dive into this. I wouldn't have bothered but this is interesting. And yes, it seems the speedup is not worth the effort.

All in all, at the stage of this project I'd rather spend time trying to make the codebase as stable as possible and as easy to contribute as possible. But little optimizations here and there are always welcome! :)

Thanks again @Hasnep for your contributions to `mpm`! 😎

**Comment by Hasnep** [comment]
Yes I agree, in my experience with these kinds of projects most of the time is spent on calling the external tools, the actual project's code is negligible by comparison. I just happened to have the code for this PR already written. Thanks for being so open to my contributions, and thanks for starting this project :)

**Pull request merged**
