### PR TITLE
Fixes to failing `mpm --pacman install <package_id>`

### PR DESCRIPTION
**Pull request by dilawar**
Before this PR.

```python 
$ mpm --pacman install vim
Package manager order: pacman
warning: No vim package found on pacman.
```

After this PR, this works!

# Fix

Fixes the parsing of the output of `pacman search` command. 

Before this patch, the `package_id` would be `extra/vim` from the regex. After this patch, the `package_id` would be `vim`. `extra/` is parsed as `repo_id` and ignored.

If pacman allows two packages with the same name but different repo e.g. `foo/vim` and `bar/vim` to co-exist then this PR is not a good solution. 

# Extra

Also adds a `.gitlab-ci.yml` file to test the package in an ArchLinux container. `gitlab-runner exec docker pacman` will run the tests inside an ArchLinux container. Can be used for #561? Unfortunately, requires installation of `gitlab-runner`. +1 that you can run the pipeline locally with gitlab-runner.  Happy to drop these changes though.

### CODE REVIEW

**Comment by kdeldycke** [comment]
Thanks @dilawar for the PR!

As you pointed out, the unittest suite is not bullet-proof and quite fragile. 90% of the work on `mpm` is trying to make it pass on GitHub CI. So yes, any tentative alternative for a better test setup is welcome. I'll keep your Docker-based proposal around as I think it will be the way to go in the future. I hope I'll be able to revisit it soon.

I'll merge your PR as-is and trust you on `pacman` fix. I'll probably cut a release in a couple of days.

**Comment by autinerd** [comment]
I'm wondering why it didn't work before :thinking: Because `pacman -Sy extra/vim` should work as well.

**Comment by kdeldycke** [comment]
I'm not a pacman user so I blindly rely on you two to decide which is the better way. Adding more tests and making the test suite robust will help us go to the bottom of it. But I don't have a clue on how to cleanly integrate Docker with GitHub workflows. 😅

**Comment by dilawar** [comment]
> 

If I remember correctly, we never reached to `pacman -S extra/vim` execution. The search function could not match `extra/vim` with `vim` and declared that there is no package. 

We still have a problem though. For example, if I have two packages from two different repos.

- Enable `bioarchlinux` and [https://software.opensuse.org//download.html?project=home%3Asubcom&package=samtools](https://software.opensuse.org//download.html?project=home%3Asubcom&package=samtools) and search for `samtools`.

```bash
[dilawars@chutki meta-package-manager (post_766)]$ poetry run mpm --pacman search samtools
╭─────────────┬──────┬─────────┬────────────────╮
│ Package ID  │ Name │ Manager │ Latest version │
├─────────────┼──────┼─────────┼────────────────┤
│ r-rsamtools │      │ pacman  │ 2.12.0-4       │
│ samtools    │      │ pacman  │ 1.16-1         │
│ samtools    │      │ pacman  │ 1.16.1-1       │
╰─────────────┴──────┴─────────┴────────────────╯
3 packages total (pacman: 3).
```

```bash
[dilawars@chutki meta-package-manager (post_766)]$ poetry run mpm --pacman install samtools
Package manager order: pacman
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click_extra/commands.py", line 142, in main
    super().main(*args, **kwargs)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click_extra/commands.py", line 175, in invoke
    return super().invoke(ctx)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dilawars/Work/GITHUB/DILAWAR/meta-package-manager/meta_package_manager/cli.py", line 727, in install
    raise ValueError("Exact search returned multiple packages.")
ValueError: Exact search returned multiple packages.
```

- Definitely need `repo_id` to be part of `package_id`.

```bash
[dilawars@chutki meta-package-manager (post_766)]$ poetry run mpm --pacman search bioarchlinux/samtools
0 package total (pacman: 0).
```

```bash
[dilawars@chutki meta-package-manager (post_766)]$ poetry run mpm --pacman search samtools
╭───────────────────────────────┬─────────────┬─────────┬────────────────╮
│ Package ID                    │ Name        │ Manager │ Latest version │
├───────────────────────────────┼─────────────┼─────────┼────────────────┤
│ bioarchlinux/package_name     │ r-rsamtools │ pacman  │ 2.12.0-4       │
│ bioarchlinux/package_name     │ samtools    │ pacman  │ 1.16.1-1       │
│ home_subcom_Arch/package_name │ samtools    │ pacman  │ 1.16-1         │
╰───────────────────────────────┴─────────────┴─────────┴────────────────╯
3 packages total (pacman: 3).
```

```bash
[dilawars@chutki meta-package-manager (post_766)]$ poetry run mpm --pacman install samtools
Package manager order: pacman
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click_extra/commands.py", line 142, in main
    super().main(*args, **kwargs)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click_extra/commands.py", line 175, in invoke
    return super().invoke(ctx)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dilawars/.cache/pypoetry/virtualenvs/meta-package-manager-fj-rdx---py3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dilawars/Work/GITHUB/DILAWAR/meta-package-manager/meta_package_manager/cli.py", line 728, in install
    raise ValueError(f"Exact search returned multiple packages: {pkg_list}")
ValueError: Exact search returned multiple packages: ['bioarchlinux/samtools', 'home_subcom_Arch/samtools']
```

_Above are my old notes before submitting the PR._

I feel that forcing only a single match by raising exceptions if there are multiple matches is a bit more strict IMO. We can print a warning and continue with the first match?! But I also appreciate that things are explicit. Maybe we can have `--strict/--no-strict` args that switch between two behaviors: on multiple matches, we throw error  in `--strict`  and we print a warning and continue with the best match (`difflib.SequenceMatcher`?) with `--no-strict`. Default being `--strict`.

**Comment by autinerd** [comment]
> If I remember correctly, we never reached to `pacman -S extra/vim` execution. The search function could not match `extra/vim` with `vim` and declared that there is no package.

Interesting. When I use pacman with "exact" search, it shows me this:
```
$ sudo pacman -Ss "^vim$"
extra/gvim 9.0.0354-1 [Installiert]
    Vi Improved, a highly configurable, improved version of the vi text editor
    (with advanced features, such as a GUI)
extra/vim 9.0.0354-1
    Vi Improved, a highly configurable, improved version of the vi text editor
```
(gvim as well because gvim provides vim)

And yeah, because a package can exist in multiple repos (the most famous being testing for versions before going to extra etc.), the repo name should be part of the package name.

The only problem is, that you can't search for "repo/package" in pacman. To check if a package exists (with repo name), you have to use `pacman -Si "extra/vim"` for this. Maybe this would be a new extension for mpm, implementing "get details about package" for the package managers.

**Pull request merged**
